frontend/package.json, frontend/src/Main/Submission/Submission.css, frontend/src/Main/Submission/submission.js
New Feature Download CSV according to selected checkbox options
Use Case 7 
Issue #7 
To test make sure to do npm install on frontend directory for new file-saver package.
- Added checkbox to select all other checkboxes
- Added Start Time checkbox 
- Added End Times checkbox
- Added Speaker checkbox
- Added isQuestion Label Checkbox
- Added Text Checkbox
- Added Only Questions Checkbox
- Renamed button to 'Export CSV'
- Handled file name input onBlur instead of onChange to reduce latency
=> Use Case 7: Feature/Download CSV options

frontend/src/Main/Submission/Submission.css, frontend/src/Main/Submission/submission.js
Tabulation of Transcript, Question Categories, Graphs
Dr. Ma wanted to tabulate these so the user wouldn't have to scroll.
Tabulated content into several tabs
1. Transcript
2. Questions
3. Question Category Distribution
4. Talking Distribution
5. Teacher Question Timeline
6. Collapsed Timeline
=> tabulated the content in submission

frontend/package-lock.json, frontend/src/Login/login.js, frontend/src/Main/MainPage.css, frontend/src/Main/SideMenu.js, frontend/src/Main/mainUserPage.js, frontend/src/SignUp/ConfirmRegister.js
UI improvement
Side menu needs to have the highlight for the active menu
"Submission" should be "Transcribe"
- Added the highlight for the active menu
- Changed "Submission" to be "Transcribe" in the side menu
- Changed the path name from /home/submission to /home/transcribe
=> Active page highlight and change Submission to Transcribe

frontend/src/Main/Submission/submission.js
Documentation
Currently, there is no form of linting. Submission.js is extremely hard to read, and a future issue is refactoring submission.js into smaller components: https://github.com/TCU-Instructional-AI/classifAI/issues/27
I have also added an issue regarding a pre-commit hook that will automatically lint code upon commit. This will be added in a future PR. 
LATER ADDITIONS: https://github.com/TCU-Instructional-AI/classifAI/issues/29
Formatted the submission.js via prettier. 
I have manually tested the submission and everything seems to work as normal.
=> Format submission.js code via prettier

frontend/src/components/Main/MyReports/MyReports.jsx
Enhancement/unfinished feature.
No Issue
- Added Youtube reports under MyReports
=> Youtube reports

frontend/package.json
Add missing dotenv package for npm run build
=> add dotenv to frontend packages

frontend/frontend.env
Make Frontend .env use new backend endpint
=> change frontend env to backend

frontend/src/components/Main/MyReports/MyReports.jsx, frontend/src/components/Main/MyReports/MyReports.module.css
Bug Fix
#104 
Removed feature to edit audio file name on Youtube since it is not compatible with youtube since youtube is not a file endpoint and doing a put request to a file endpoint will fail.
- Removed Editing Audio File Name for Youtube since it is not compatible with youtube since youtube does not use file endpoint
- Updated my reports to use audioFile to get Youtube title
- Disabled Download button for Youtube Links
=> Bug/Editing Reports causes Error 

backend/routes/fileUploadRoute.js, backend/routes/reportRoutes.js, backend/routes/reportUploadRoute.js
fixed categorize endpoint logic 
added file size
=> Fix categorize endpoint, possible file size limit fix

frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> prevent early checks on status

frontend/src/components/Main/WhisperModel/CollapsedTimeline.jsx, frontend/src/components/Main/WhisperModel/CsvOptions.jsx, frontend/src/components/Main/WhisperModel/TeacherQuestionTimeline.jsx
Bug Fix and Enhancement: Question Time Line uses Words NA, Low, Medium, High instead of 0-3. Also updated CSV to use that.
no issue
- Question Time Line uses Words NA, Low, Medium, High instead of 0-3.
- Also updated CSV to use words
- Fixed Bug where timeline was not pointing to the right question
=> fixed questiontimeline to use word levels

frontend/src/components/Main/WhisperModel/SaveChanges.jsx
=> refactor to use multipart and detailed errors

frontend/src/components/Main/WhisperModel/SaveChanges.jsx
=> dont json stringify

frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> list all statuses for progress bar

frontend/src/components/Main/WhisperModel/CollapsedTimeline.jsx, frontend/src/components/Main/WhisperModel/TeacherQuestionTimeline.jsx
=> gaps slightly more appararent

frontend/src/components/Main/MyReports/MyReports.jsx, frontend/src/components/Main/MyReports/MyReports.module.css
=> working youtube link button

frontend/src/components/Main/WhisperModel/SaveChanges.jsx
=> restore json logic

frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> upload and save to same format

backend/routes/reportRoutes.js, frontend/src/components/Main/WhisperModel/SaveChanges.jsx
Bug fix: Multipart frontend and backend support
=> working multipart

frontend/src/components/Main/WhisperModel/Analyze.jsx, frontend/src/components/Main/WhisperModel/ReportInfo.jsx, frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> disable meta deta during analysis and notify user upon successful upload

frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> no longer recommend leaving the page

frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> update youtube validation to allow mobile

frontend/src/components/Main/ExportDataFiles/ExportDataFiles.jsx, frontend/src/components/Main/MyReports/MyReports.jsx, frontend/src/components/Main/WhisperModel/ReportInfo.jsx, frontend/src/components/Main/WhisperModel/SaveChanges.jsx, frontend/src/components/Main/WhisperModel/UploadRecording.jsx
=> MUI tables

frontend/src/components/Login/ResetPassword.jsx
=> error handling

frontend/src/components/Main/ExportDataFiles/ExportDataFiles.jsx, frontend/src/components/Main/MyReports/MyReports.jsx
=> mention use of tooltip

frontend/src/components/Main/WhisperModel/Analyze.jsx, frontend/src/components/Main/WhisperModel/FullTranscript.jsx
=> transcript text and speaker re renders categorized questions
